version: '3'
services:
  meetscript:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Persist your Selenium profile.
      - selenium_profile:/tmp/selenium_profile
      # Mount the host's PulseAudio socket so the container can connect.
      - "/tmp/pulse:/tmp/pulse"
    environment:
      - MEET_URL=${MEET_URL}
      - GOOGLE_USERNAME=${GOOGLE_USERNAME}
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - EDGE_DRIVER_PATH=/usr/local/bin/msedgedriver
      # Tell applications where to find the PulseAudio server.
      - PULSE_SERVER=tcp:host.docker.internal:4713
volumes:
  selenium_profile: